from __future__ import annotations

DEFAULT_KGX_STORAGE_BASE_URL = "https://kgx-storage.ci.transltr.io/releases"
DEFAULT_REQUESTS_TIMEOUT_SECONDS = 20.0
DEFAULT_REMOTE_METADATA_MAX_BYTES = 64 * 1024 * 1024
DEFAULT_TOP_COUNT = 40

ALL_SUBJECT_CATEGORIES_VALUE = "__all_categories__"
ALL_CATEGORY_SANKEY_TOP_N = 40
SUBJECT_CATEGORY_SANKEY_TOP_N = 200
SOURCE_PREDICATE_SANKEY_TOP_N = 100